# Site settings
title: Acua
email: Acua@acuabar.com
description: >- 
  Acua Baja Bar & Mar
  Restaurante-Bar con un gran ambiente y comida de la mejor calidad.
  Clientes contentos siempre.

baseurl: ""
url: "https://acuabar.com/" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-162867542-4
lang: en_us

minima:
  date_format: "%-d de %B del %Y"

social:
  name: Acua
  links:
    - https://www.facebook.com/acuabajabarymar
    - https://www.instagram.com/acuabajamar/

# Build settings
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - package-lock.json
  - package.json
  - gulpfile.js
  - img-temp/

defaults:
  -
    scope:
      path: ""
    values:
      lang: "en_us"
      lazy: true
      image:
        path: /assets/img/acua/og512x512.png
        height: 512
        width: 512



